source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TTGTagCollectionView_Example', :exclusive => true do
  pod "TTGTagCollectionView", :path => "../"
end

target 'TTGTagCollectionView_Tests', :exclusive => true do
  pod "TTGTagCollectionView", :path => "../"

  
end
