source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '11.0'

target 'TTGTagCollectionView_Example' do
  pod 'TTGTagCollectionView', :path => '../'
  pod 'Masonry', :git => 'git@github.com:SnapKit/Masonry.git', :tag => 'v1.1.0'
  pod 'SVPullToRefresh', :git => 'git@github.com:samvermette/SVPullToRefresh.git', :tag => '0.4.1'

  target 'TTGTagCollectionView_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
